### ISSUE TITLE
Start Video

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-adjacent#5]
For any of these that involve a video we should have the reader "opt in" to starting the video. 

@stephkoltun do you think it makes sense to do a separate image embed to the side or perhaps what makes sense is to have the page load with a static image demonstrating the idea and then a button to start making it interactive?

**Comment by stephkoltun** [comment]
I think the second option (page load with the state image and then button for interaction) is ideal. That way, even if someone doesn't interact with it, the point is still evident visually.

**Comment by shiffman** [comment]
Completed for https://ml5js.github.io/ml5-adjacent/02_ImageClassification_Video/ (waiting for github pages build)

**Comment by shiffman** [comment]
<img width="359" alt="screen shot 2018-06-14 at 3 55 01 pm" src="https://user-images.githubusercontent.com/191758/41434937-5747a58a-6feb-11e8-9f88-628b4edcc848.png">

Happy to have someone else model! Also, we should have the text match in this case "broccoli".

**Comment by shiffman** [comment]
Closing as this is now implemented for both image classification and posenet. I also have a start mic for the crepe example.
