### ISSUE TITLE
poseNet with "preview" image?

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-adjacent#9]
@oveddan can you take a look at this sketch? (It's for an embed demo in the adjacent article).

https://github.com/ml5js/ml5-adjacent/tree/master/07_PoseNet

I'm trying to get it to work with a sample starter image then the user can press a button to start detecting poses from the video. Right now it works but I'm not getting any results for the starter image (which is just a placeholder, so maybe a bad image?)

**Comment by oveddan** [comment]
If you step through the ml5 posenet code [here](https://github.com/ml5js/ml5-library/blob/master/src/PoseNet/index.js#L104) video never gets assigned to.  This is because it is not built to currently handle images.  We should update the ml5 `posenet` call to handle images.

**Comment by shiffman** [comment]
Ah, ok! Let's "fake it" with a static image that has the dots in it already. . do you have a good suggestion for a 320x240 image that shows off posenet well? 

How about?

http://www.danioved.com/images/posenet.gif

**Comment by cvalenzuela** [comment]
The current method does support images but not in the constructor. This is because 
the idea is to give a video only when the `singlePose` or `multipose` is going to be called recurrently.

So for a video input this works:

```javascript
const poseNet = ml5.poseNet(video, 'single', gotPoses);

function gotPoses() { /* */ }
```

And for an image
```javascript
const poseNet = ml5.poseNet('single');

// mulitPose works too
poseNet.singlePose(img, gotPoses)

function gotPoses() { /* */ }
```

**Comment by oveddan** [comment]
@cvalenzuela just tried to do this like the code above, but it throws an error when 'net' isn't loaded yet.

<img width="1029" alt="screen shot 2018-06-14 at 5 48 19 pm" src="https://user-images.githubusercontent.com/891755/41440084-2d94c762-6ffb-11e8-85da-16d2bd97edfc.png">

**Comment by cvalenzuela** [comment]
Yes, there's a bug there! thanks @oveddan!

**Comment by shiffman** [comment]
Addressing in #12

**Comment by shiffman** [comment]
All set with #13

**Comment by marshalhayes** [comment]
> Yes, there's a bug there! thanks @oveddan!

Hi @cvalenzuela. I'm having this same problem when using p5's `loadImage()`. This is a snippet from my code that I think is causing the error: (I'm using p5's instance mode if that matters)
```
var s = function(sketch) {
  let img;
  let poseNet;
  let poses = [];
  let skeletons = [];

  sketch.preload = function() {
    img = sketch.loadImage('images/man.jpg');
  }

  sketch.setup = function() {
    poseNet = ml5.poseNet('single');

    poseNet.singlePose(img, sketch.gotPoses);
    poseNet.on('pose', function(results) {
      poses = results;
    });
  };

  sketch.draw = function() {
    sketch.image(img, 0, 0);
  };

  sketch.gotPoses = function(p) {
    console.log(p);
  }
};
```

**Comment by cvalenzuela** [comment]
which ml5 version are you using?

**Comment by marshalhayes** [comment]
Sorry, forgot to include that. I'm using this one: [https://unpkg.com/ml5@0.1.1/dist/ml5.min.js](https://unpkg.com/ml5@0.1.1/dist/ml5.min.js)
